server {
  listen 80;
  listen 443 ssl http2;
  server_name charts.wsd80.top;
  access_log /data/logs/charts.wsd80.top.log;
  error_log /data/logs/charts.wsd80.top-error.log;

  include /etc/nginx/conf.d/https/wsd80.conf;
  error_page 497 https://$host$request_uri;

  location / {
    proxy_pass http://charts.stage.vip;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Nginx-Proxy true;
    proxy_set_header Connection "";
    # 反向代理https时需要添加以下内容
    proxy_ssl_server_name on;
    proxy_ssl_name charts.stage.vip;
    proxy_set_header Host charts.stage.vip;
  }
}
